import React from 'react';
import { Send, FileEdit } from 'lucide-react';

export default function OutreachPage() {
  return (
    <div className="space-y-8 text-slate-100">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white md:text-4xl">Outreach Sequences</h1>
        <p className="mt-2 text-sm text-slate-400">
          Review, edit, and approve personalized email and LinkedIn campaigns generated by the Outreach Agent.
        </p>
      </div>

      {/* Grid containing email draft cards */}
      <div className="grid gap-6 md:grid-cols-2">
        <div className="rounded-2xl border border-slate-800 bg-slate-900/30 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-950 text-indigo-400 border border-indigo-900/50">
                Email Step 1 (Cold)
              </span>
              <span className="text-xs text-slate-500 font-medium">Stripe Outbound Campaign</span>
            </div>
            
            <div className="mt-4 p-4 rounded-xl bg-slate-950 border border-slate-900 text-xs font-mono text-slate-300 space-y-2">
              <p><strong className="text-slate-500">Subject:</strong> Solving cross-border transaction latency at STRIPE</p>
              <hr className="border-slate-900 my-2" />
              <p>Hi there,</p>
              <p>I noticed that STRIPE is expanding payments globally following your Series B funding. We specialize in helping tech platforms optimize transaction routing paths...</p>
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-slate-800 border border-slate-700 text-slate-200 rounded-xl text-xs font-semibold hover:bg-slate-700 transition-colors">
              <FileEdit className="h-4 w-4" /> Edit
            </button>
            <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-xl text-xs font-semibold hover:bg-indigo-500 transition-colors">
              <Send className="h-4 w-4" /> Approve & Queue
            </button>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-900/30 p-6 flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between">
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-950 text-blue-400 border border-blue-900/50">
                LinkedIn Step 2 (Connect)
              </span>
              <span className="text-xs text-slate-500 font-medium">HubSpot Outbound Campaign</span>
            </div>
            
            <div className="mt-4 p-4 rounded-xl bg-slate-950 border border-slate-900 text-xs font-mono text-slate-300 space-y-2">
              <p>Hi! Congrats on the Series B expansion at HubSpot. I saw you are scaling operations globally. Let us connect if you are exploring automated sales workflows!</p>
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-slate-800 border border-slate-700 text-slate-200 rounded-xl text-xs font-semibold hover:bg-slate-700 transition-colors">
              <FileEdit className="h-4 w-4" /> Edit
            </button>
            <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-xl text-xs font-semibold hover:bg-indigo-500 transition-colors">
              <Send className="h-4 w-4" /> Approve & Queue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
