import React from 'react';
import { Send, FileEdit } from 'lucide-react';

export default function OutreachPage() {
  return (
    <div className="space-y-8 text-slate-100">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white md:text-4xl">
          Outreach Sequences
        </h1>
        <p className="mt-2 text-sm text-slate-400">
          Review, edit, and approve personalized email and LinkedIn campaigns generated by the
          Outreach Agent.
        </p>
      </div>

      {/* Grid containing email draft cards */}
      <div className="grid gap-6 md:grid-cols-2">
        <div className="flex flex-col justify-between rounded-2xl border border-slate-800 bg-slate-900/30 p-6">
          <div>
            <div className="flex items-center justify-between">
              <span className="rounded-full border border-indigo-900/50 bg-indigo-950 px-2.5 py-0.5 text-xs font-semibold text-indigo-400">
                Email Step 1 (Cold)
              </span>
              <span className="text-xs font-medium text-slate-500">Stripe Outbound Campaign</span>
            </div>

            <div className="mt-4 space-y-2 rounded-xl border border-slate-900 bg-slate-950 p-4 font-mono text-xs text-slate-300">
              <p>
                <strong className="text-slate-500">Subject:</strong> Solving cross-border
                transaction latency at STRIPE
              </p>
              <hr className="my-2 border-slate-900" />
              <p>Hi there,</p>
              <p>
                I noticed that STRIPE is expanding payments globally following your Series B
                funding. We specialize in helping tech platforms optimize transaction routing
                paths...
              </p>
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <button className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-4 py-2 text-xs font-semibold text-slate-200 transition-colors hover:bg-slate-700">
              <FileEdit className="h-4 w-4" /> Edit
            </button>
            <button className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-indigo-500">
              <Send className="h-4 w-4" /> Approve & Queue
            </button>
          </div>
        </div>

        <div className="flex flex-col justify-between rounded-2xl border border-slate-800 bg-slate-900/30 p-6">
          <div>
            <div className="flex items-center justify-between">
              <span className="rounded-full border border-blue-900/50 bg-blue-950 px-2.5 py-0.5 text-xs font-semibold text-blue-400">
                LinkedIn Step 2 (Connect)
              </span>
              <span className="text-xs font-medium text-slate-500">HubSpot Outbound Campaign</span>
            </div>

            <div className="mt-4 space-y-2 rounded-xl border border-slate-900 bg-slate-950 p-4 font-mono text-xs text-slate-300">
              <p>
                Hi! Congrats on the Series B expansion at HubSpot. I saw you are scaling operations
                globally. Let us connect if you are exploring automated sales workflows!
              </p>
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <button className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-4 py-2 text-xs font-semibold text-slate-200 transition-colors hover:bg-slate-700">
              <FileEdit className="h-4 w-4" /> Edit
            </button>
            <button className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-indigo-500">
              <Send className="h-4 w-4" /> Approve & Queue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
